stages:
  - build-petsc
  - pflotran
#  - pflotran-interface
  - ci_status

image: docker:latest

services:
  - docker:dind

variables:
  GIT_DEPTH: 10
  GIT_STRATEGY: fetch
  DOCKER_DRIVER: "overlay2"
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HOST: tcp://docker:2375
  # Use TLS https://docs.gitlab.com/ee/ci/docker/using_docker_build.html#tls-enabled
  DOCKER_HOST: tcp://docker:2376
  DOCKER_TLS_CERTDIR: "/certs"

before_script:
  - apk add --no-cache bash curl
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY

build-petsc:
  stage: build-petsc
  script:
    - BUILD_STATUS=running BUILD_KEY=push ./.gitlab/build_status
    - docker --version
    - export PETSC_VERSION=$(cat ./.gitlab/petsc-git-version.txt)
    - export IMAGE=$CI_REGISTRY_IMAGE:$PETSC_VERSION
    - docker pull $IMAGE || true
    - >
      docker build 
      -f ./.gitlab/dockerfile-petsc 
      --build-arg PETSC_VERSION=$PETSC_VERSION
      --cache-from $IMAGE
      --tag $IMAGE
      .
    - docker push $IMAGE
    # copy log files from image by launching container, copying
    # and destorying the container
    - id=$(docker create $IMAGE)
    - docker cp $id:/scratch/petsc/*.log .
    - docker rm -v $id
  artifacts:
    paths:
      - "*.log"

pflotran:
  stage: pflotran
  script:
    - BUILD_STATUS=running BUILD_KEY=push ./.gitlab/build_status
    - export PETSC_VERSION=$(cat ./.gitlab/petsc-git-version.txt)
    - export IMAGE=$CI_REGISTRY_IMAGE:$PETSC_VERSION
    - export NEW_IMAGE=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker pull $IMAGE || true
    - >
      docker build 
      -f ./.gitlab/dockerfile-pflotran
      --build-arg IMAGE=$IMAGE
      --cache-from $IMAGE
      --tag $NEW_IMAGE
      .
    # copy regression results from image by launching container, copying
    # and destorying the container
    - id=$(docker create $NEW_IMAGE)
    - docker cp $id:/scratch/regression_tests .
    - docker rm -v $id
  artifacts:
    paths:
      - regression_tests

.pflotran-interface:
  stage: pflotran-interface
  script:
    - BUILD_STATUS=running BUILD_KEY=push ./.gitlab/build_status
    - export PETSC_VERSION=$(cat ./.gitlab/petsc-git-version.txt)
    - export IMAGE=$CI_REGISTRY_IMAGE:$PETSC_VERSION
    - export NEW_IMAGE=$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker pull $IMAGE || true
    - >
      docker build 
      -f ./.gitlab/dockerfile-pflotran-interface
      --build-arg IMAGE=$IMAGE
      --cache-from $IMAGE
      --tag $NEW_IMAGE
      .
    - id=$(docker create $NEW_IMAGE)
    - docker cp $id:/scratch/src/clm-pflotran/regression_test .
    - docker cp $id:/scratch/src/clm-pflotran/pflotran-tests-* .
    - docker rm -v $id
  artifacts:
    paths:
      - pflotran-tests-*
      - regression_tests

success:
  stage: ci_status
  before_script:
    - apk add --no-cache bash curl
  after_script:
    - ""
  script:
    - env
    - BUILD_STATUS=passed BUILD_KEY=push ./.gitlab/build_status
  when: on_success

failure:
  stage: ci_status
  before_script:
    - apk add --no-cache bash curl  
  after_script:
    - ""
  script:
    - BUILD_STATUS=failed BUILD_KEY=push ./.gitlab/build_status
  when: on_failure
